### PR TITLE
WIP - Lagrangian gauges test - don't merge

### PR DESCRIPTION
**Pull request by rjleveque**
Don't merge this, I'm just testing to see if travis tests pass with all changes from clawpack/geoclaw#423 and related PRs on amrclaw,pyclaw, and visclaw.

### CODE REVIEW

**Comment by rjleveque** [comment]
Successful, all tests pass.

**Comment by rjleveque** [comment]
To test some new commits.

**Comment by rjleveque** [comment]
@mandli: The problem was that I removed a final call to print_gauges, thinking this was always done after calling valout at the final time. However, this test problem has `clawdata.num_output_times=0` so the final frame is not output and neither were gauges.  I put back the final call to print_gauges since there may be cases where the user only cares about gauges and doesn't want to output the frames.

My other problem with running it locally was that `ike.storm` was not in the expected place until I changed `setrun.py` to specify `os.path.abspath("ike.storm")`.  But a better solution might be to change `data.py` so that it handles these files the same way it handles topofiles and dtopofiles, replacing relative paths with absolute paths before writing to the `.data` file?

**Comment by mandli** [comment]
Works for me now as well.  This extra call was something that we had to work on for awhile as we could not record the initial gauge locations reliably until `b4step` was called and the `aux` values were properly set so had to mangle everything.

In terms of the other issue, `ike.storm` is a "computed" file, similar to how a fictitious topo file would be. so that does make some sense.  The other problem though is that in order to construct `ike.storm` we try to download another file that we read in and create `ike.storm` hence I think the confusion.

**Comment by rjleveque** [comment]
Which reminds me that we still don't record the final time in the gauge files, another thing to fix eventually.  Especially for particle tracking it would be nice to have the last location.

Regarding `ike.storm`, in the examples version it uses:

    data.storm_file = os.path.expandvars(os.path.join(os.getcwd(),
                                         'ike.storm'))

Could also do this in the test, but again maybe `data.py` should add this as it does for topofiles.

**Comment by mandli** [comment]
Sounds like a good idea.  Do you want to make the change in this PR?

**Comment by rjleveque** [comment]
The tests are passing now, so it would be better to do that as a separate PR since it's unrelated to the new lagrangian gauges (once I fixed my bug).

**Comment by mandli** [comment]
I just opened an issue clawpack/geoclaw#426 for this.

**Pull request closed without merging**
